version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis

  celery_worker:
    build: .
    command: celery -A celery_app_worker worker --concurrency=5 -n worker1
    container_name: celery_worker
    depends_on:
      - redis

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker


